name: marshalling
version: 0.1.0-dev
author: Andrew Mezoni <andrew.mezoni@gmail.com>
description: The marshalling library allows to marshal and unmarshal (also serialize/deserialize) an objects (e.g. into json compatible types)
environment:
  sdk: '>=2.3.0 <3.0.0'
dependencies:
dev_dependencies:  
  pedantic: any
  test: any