name: marshalling
version: 0.1.2
author: Andrew Mezoni <andrew.mezoni@gmail.com>
description: The marshalling library allows to marshal and unmarshal (also serialize/deserialize) an objects (e.g. into json compatible types)
homepage: https://github.com/mezoni/marshalling
environment:
  sdk: '>=2.3.0 <3.0.0'
dependencies:
dev_dependencies:  
  pedantic: any
  path: any
  test: any
  yaml: any